---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.19.2
        name: prometheus
        ports:
          - name: port9090
            containerPort: 9090
        volumeMounts:
          - mountPath: "/etc/prometheus"
            name: prometheus-data-pvc 
      volumes:
        - name: prometheus-data-pvc
          persistentVolumeClaim:
            claimName: prometheus-pvc
