---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-ceph-hdd-dp1
  resources:
    requests:
      storage: 5Gi
  hostPath:
    path: "/prometheus"
