---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: postgres-container
    #tier: backend  
  ports:
  - name: postgres-ports
    protocol: TCP
    port: 80 
    targetPort: 5432
#  type: ClusterIP
