---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  strategy:
    #rollingUpdate:
    #  maxSurge: 1
    #  maxUnavailable: 0
    #type: RollingUpdate
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-container
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        ports:
          - name: postgres-port
            containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                 name: postgres-config
                 key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef: 
                 name: postgres-config
                 key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom: 
              configMapKeyRef: 
                 name: postgres-config
                 key: POSTGRES_PASSWORD            
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-data-pvc 
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 400Mi
        #  limits:
        #    cpu: 100m
        #    memory: 400Mi
      volumes:
        - name: postgres-data-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
