---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-ceph-hdd-dp1
  resources:
    requests:
      storage: 10Gi
